{
 "title": "New dashboard Copy",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CPULA",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load15", "legendFormat": "CPULA 15" },
    { "expr": "node_load5", "legendFormat": "CPULA 5" },
    { "expr": "node_load1", "legendFormat": "CPULA 1" }
   ]
  },
  {
   "title": "Free memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes/1024/1024/1024",
     "legendFormat": "Free memory GB"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100-irate(node_cpu_seconds_total{job=\"nodeexporter\",mode=\"idle\"}[30s])*100"
    }
   ]
  },
  {
   "title": "free disk spase",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=\"nodeexporter:9100\",mountpoint=\"/\",fstype!=\"rootfs\"}/1024/1024/1024"
    }
   ]
  }
 ]
}